build-gradle:
	gradle build

run-gradle:
	java -jar build/libs/rs-api-multi-auth-server-1.0-SNAPSHOT.jar

build-run-gradle: build-gradle run-gradle

build-maven:
	mvn clean install

run-maven:
	java -jar target/rs-api-multi-auth-server-1.0-SNAPSHOT.jar

build-run-maven: build-maven run-maven

